//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPPLWeb.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DPPL_DbEntities : DbContext
    {
        public DPPL_DbEntities()
            : base("name=DPPL_DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<M_CategoryMaster> M_CategoryMaster { get; set; }
        public virtual DbSet<M_MasterTable> M_MasterTable { get; set; }
        public virtual DbSet<M_PartyMaster> M_PartyMaster { get; set; }
        public virtual DbSet<M_ProductMaster> M_ProductMaster { get; set; }
        public virtual DbSet<T_InvoiceInfo> T_InvoiceInfo { get; set; }
        public virtual DbSet<T_TransactionInfo> T_TransactionInfo { get; set; }
    }
}
