//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPPLWeb.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_InvoiceInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_InvoiceInfo()
        {
            this.T_TransactionInfo = new HashSet<T_TransactionInfo>();
        }
    
        public int InvoiceID { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public int PartyID { get; set; }
        public string Delivery_Location { get; set; }
        public string LR_No { get; set; }
        public string Cases { get; set; }
        public string Transport { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<double> SubTotal { get; set; }
        public Nullable<double> Dis_Percent { get; set; }
        public Nullable<double> IGST { get; set; }
        public Nullable<double> FREIGHT { get; set; }
        public Nullable<double> RoundOff { get; set; }
        public Nullable<double> CR_DR_Note { get; set; }
        public double GrandTotal { get; set; }
        public string GrandTotal_InWord { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Active { get; set; }
    
        public virtual M_PartyMaster M_PartyMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_TransactionInfo> T_TransactionInfo { get; set; }
    }
}
